### ISSUE TITLE
Use Parcel instead of Webpack

### ISSUE THREAD

**Issue by ry** [propelml/propel#120]
It's much faster. https://parceljs.org/

**Comment by ry** [comment]
1f7f9e54bfa135213193b6aeb509e95e2f916bc8

**Comment by TheLarkInn** [comment]
What if those numbers weren't forthcoming. Would you take a PR to us webpack instead? :bow:

**Comment by ry** [comment]
@TheLarkInn No, sorry. We just spent a bunch of effort to convert to parcel and we're happy with it.

**Comment by TheLarkInn** [comment]
No worries!! Thanks for the quick response!
