### ISSUE TITLE
http://propelml.org/docs/#Tensor_cosh Broken on mobile

### ISSUE THREAD

**Issue by ry** [propelml/propel#198]

**Comment by ry** [comment]
Awesome - contributions welcome! 

On my iPhone/Safari the plot doesn't display on page load.

<img src="https://i.imgur.com/BgJjmUa.jpg">

**Comment by Qti3e** [comment]
So...  
I guess it's a problem with [`nb.Cell`](https://github.com/propelml/propel/blob/master/notebook.ts#L76) class.
(More specifically I think it's [notebookExecuteQueue](https://github.com/propelml/propel/blob/master/notebook.ts#L150))

But, do the plots work fine when you click on run? if so...

We can fix it in the standard way, but what about some hack like this:
```js
const iOS = !!navigator.platform && /iPad|iPhone|iPod/.test(navigator.platform);
if(iOS){
    setTimeout(function(){
        document.querySelectorAll('.buttons > .run-button').forEach(x => x.click())
     }, 2000)
}
```

**Comment by ry** [comment]
Thanks for investigating - seems likely it is notebookExecuteQueue. But the source of the bug should be fixed, not a hack like that.
