### ISSUE TITLE
Contextify running code in notebooks

### ISSUE THREAD

**Issue by qti3e** [propelml/propel#233]
Hi,
How about containerizing notebooks' papers? (I don't know what to call it, project. paper, users code, ...)
It allows users to have multiple open containers at once in one tab and of course not touching global variables.
In the Node.js environment, it's possible using VM module, but I know notebooks are about the browser, so I wrote a simple implementation of VM module with all standard APIs for the web :smiley: 
Code: [CrossVM](https://github.com/qti3e/crossvm)
If you like the idea behind it I can implement it as an internal dependency in this project.
(And if you ever wondered to use this package (Which I guess you won't), it's good to know it has only one dependency that you already have on this project (acorn))

(Also I'm thinking of implementing this as a web worker so users can be sure their code is running in the background, and re-use that container after a short while (without losing randomly generated data))
Regards.

**Comment by piscisaureus** [comment]
Fixed: https://github.com/propelml/propel/commit/e3ef25998f2b10310df30026a0d8ca5fa6d60996 (#292)
