### ISSUE TITLE
Adding non-code blocks with markdown support to write complete articles

### ISSUE THREAD

**Issue by Qti3e** [propelml/propel#239]
There is an npm package containing a React Component to make job easier [react-markdown](https://github.com/rexxars/react-markdown)

**Comment by Qti3e** [comment]
I looked for the best package we can use and I found [markdown](https://www.npmjs.com/package/markdown), it's dependency map ends up with only 5 dependencies and it's very light (+224K to node_module, but minified bundle would be much smaller (+90K is not even required and only exists))

**Comment by ry** [comment]
I'm not sure if I want this feature. We should definitely have an editable title, and maybe description,
 but I think people could write explanations in comments. (I'm open minded to it - just not right now.) Thanks for bringing it up tho.
