### ISSUE TITLE
"Create Empty Notebook" button doesn't work when not signed in.

### ISSUE THREAD

**Issue by ry** [propelml/propel#265]

**Comment by ryanmurakami** [comment]
@ry What's the desired behavior here? Should we allow anonymous notebooks and just have them be anonymous, or should we disable the button and display it differently, or should we message that the user should sign in?

**Comment by ry** [comment]
I think it would be nice to have anonymous notebooks - for one off things. Ideally there'd be some indication to the user that their work isn't being saved unless logging in (which we also need for when people edit other people's notebooks)

**Comment by ryanmurakami** [comment]
This can be closed with #335 merged.
