### ISSUE TITLE
propel.tensor is not a function on Windows

### ISSUE THREAD

**Issue by tejzpr** [propelml/propel#290]
I get an error when I try to access propel.tensor in windows. I am using the propel_windows package.
Code:
`
import { tensor } from "propel";
const f = (x) => tensor(42).mul(x);
console.log(f(1));
`
Error:
`
TypeError: propel_1.tensor is not a function
`

**Comment by ry** [comment]
Docs and released npm package aren't synced at the moment. Previously the "tensor" function was called "T", which should work.

```
import { T } from "propel"; const f = (x) => T(42).mul(x); console.log(f(1));
```

We'll be releasing a new version tomorrow. Sorry about that.
