### ISSUE TITLE
Notebook allows last cell to delete

### ISSUE THREAD

**Issue by ryanmurakami** [propelml/propel#323]
When inside a notebook, the last cell gives a user the option to delete the cell.
![screen shot 2018-03-05 at 3 44 19 pm](https://user-images.githubusercontent.com/767105/37004036-5198ce6a-208c-11e8-9365-c88c741447a7.png)
When the user clicks delete, the notebook goes into an error state that cannot be recovered without refreshing:
![screen shot 2018-03-05 at 3 44 26 pm](https://user-images.githubusercontent.com/767105/37004078-79283f06-208c-11e8-80fa-9563d04da04f.png)
Expected experience is to not have the delete option on the last cell in a notebook.

**Comment by ry** [comment]
Good catch! I guess that button just shouldn't be displayed if the cell count == 1
