### ISSUE TITLE
outputHandler can not post canvas to main window

### ISSUE THREAD

**Issue by qti3e** [propelml/propel#339]
```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': #<WeakMap> could not be cloned.
```

**Comment by piscisaureus** [comment]
Why is this a problem? I don't expect canvas to be passed. It's contents needs to be serialized.

**Comment by qti3e** [comment]
@piscisaureus yes, you're right, and I meant that, but I think it's a bug in serializing tensor data or sth related to the canvas.
By using `imshow` you'll get that error, I might fix it at the end of the day.

ps: we switched to sending the tensor itself instead of an object containing a Uint8ClampedArray at #337, might it be the root of this bug?
