### ISSUE TITLE
AMD and Intel GPU support?

### ISSUE THREAD

**Issue by blaesus** [propelml/propel#428]
Propel is propelled by Tensorflow, whose GPU mode only works on nVidia cards officially (https://github.com/tensorflow/tensorflow/issues/22).
Am I right to understand that Propel's GPU acceleration doesn't work on AMD and Intel cards yet?

On a higher level of abstraction, Keras has a backend called PlaidML (https://github.com/plaidml/plaidml) that supports OpenCL, which I experimented with and seems to work on my Radeon. I wonder if similar support is in horizon for Propel?

**Comment by ry** [comment]
That's right - we don't support AMD nor Intel at the moment with the TF backend. However, we do have GLSL implementations of everything thanks to our deeplearn.js backend and thus we think it's possible to run node-webgl. See #313.
