### ISSUE TITLE
Output of cell is too verbose 

### ISSUE THREAD

**Issue by ry** [propelml/propel#438]
This example should have a one-line output `[16, 28, 28]`. Instead it has a 5 line output.

```
images.shape

[
  16,
  28,
  28
]
```

http://propelml.org/notebook/?nbId=yQW73rabuUBeTa72OiHL

See also #276

**Comment by qti3e** [comment]
Started #276 at [q/inspector](https://github.com/qti3e/propel/tree/q/inspector)

**Comment by ry** [comment]
closed in favor of #276
