### ISSUE TITLE
Params interface doesn't show up in docs.

### ISSUE THREAD

**Issue by ry** [propelml/propel#469]
The bug is somewhere in https://github.com/propelml/propel/blob/master/tools/gendoc.ts

**Comment by dangerdak** [comment]
[params.ts](https://github.com/propelml/propel/blob/1e76e609ae099898c8e2573a2809927fb5175f62/src/params.ts#L33) exports an interface and [gendoc.ts doesn't visit interfaces](https://github.com/propelml/propel/blob/master/tools/gendoc.ts#L182).
I tried adding a `visitInterface` function (a slightly modified version of [visitClass](https://github.com/propelml/propel/blob/1e76e609ae099898c8e2573a2809927fb5175f62/tools/gendoc.ts#L268) - just so it accepts the right types) but then all of these interfaces show up in the docs which seems undesirable:
```
interface Params
interface ParamsFn
interface ExperimentOpts
interface Promise
interface SGDOpts
interface MinimizeResult
interface Array
interface Storage
interface FormatOptions
interface PoolOpts
interface LinearOpts
interface ConvOpts
interface BatchNormOpts
interface TensorOpts
interface ConvOpts
```

**Comment by ry** [comment]
Cool - thanks for looking into this. Those are all public interfaces - I'd say let's start with having them all in the docs - and then later devise a way to minimize noise in the index...  I can think of a few strategies for that - one could be a special jsdoc comment that makes an interface not get displayed. Or, maybe it would be better to have a way to attach the documentation for an interface to a method. For example, in the case of PoolOpts or ConvOpts it would be ideal to list the structure inside the maxPool() or conv2d() methods respectively. In any case, it's more correct to display all the public interfaces than it is to not display them, so let's start with that.

**Comment by ry** [comment]
Thanks @dangerdak! I enjoyed [your blog post](https://medium.com/yld-engineering-blog/machine-learning-in-javascript-with-propel-50bfa46e8b03) too!

**Comment by dangerdak** [comment]
Thanks dude :)
