### ISSUE TITLE
Propel vs. Tensorfow.js

### ISSUE THREAD

**Issue by somombo** [propelml/propel#498]
> This is not a bug or feature request.. Just hopefully some insightful discussion about the possible direction of the project.

Official Javascript support for tensorflow in the browser was recently announced (Deeplearnjs has now become Tensorflowjs). https://youtu.be/YB-kfeNIPCE 

> Note that node.js support is on the way https://js.tensorflow.org/faq

How does this project plan to differentiate itself seeing as it appears to have aimed at providing what  TF.js is providing (or will provide) whilst also being strongly dependent  on tensorflow?

**Comment by ry** [comment]
There is certainly some overlap in goals... I will put out a more detailed roadmap soon - but we are trying to tie together the core framework with a system to inspect training models in real-time with plots and interactive notebooks for one-off calculations (think juypter+matplotlib+tensorboard+Tf all integrated together). We expect training to be done primarily outside of browsers - so we are building features for checkpointing and streaming large datasets.

I think it’s too soon to say which directions either of these frameworks will ultimately go in - but I would say that Propel is aiming more towards tooling around building debugging and analyzing models completely inside of JavaScript.

I’ll update this issue with a link to our roadmap once I put it up.

**Comment by ry** [comment]
Here's an update
https://github.com/propelml/propel/blob/06a58afb6582cdcbd2c3bc0a6529bf5d4ca17bf7/README.md
