### ISSUE TITLE
Error: TFE_TensorHandle can be resolved iff it is on CPU

### ISSUE THREAD

**Issue by opjlmi** [propelml/propel#505]
I tried to use the 3000 items array into tensor function[(the codes on notebook)](http://propelml.org/notebook/?nbId=gUNaeFowRcowrxZaW4QV), and it works on propel notebook website.

But I run the codes on my local server, it will show the error `Error: TFE_TensorHandle can be resolved iff it is on CPU (this handle is on /job:localhost/replica:0/task:0/device:GPU:0). Consider using TFE_TensorHandleCopyToDevice to get a copy of the tensor on CPU` when exec the `signal.data()` function.

**Comment by ry** [comment]
Sorry - I hadn’t a chance to investigate this - what was the issue?

**Comment by opjlmi** [comment]
It's okay. That beacuse I init the tensor data in gpu storge.
So when I run `tensor.data()` will failed.
Should use `tensor.cpu().data()` will work.
