### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by trivikr** [propelml/propel#518]
As propelml is recommending to use tfjs in it's README, should this repo be archived?
Github documentation on Archiving: https://help.github.com/articles/archiving-repositories/

**Comment by trivikr** [comment]
Any update?

**Comment by Maxim-Mazurok** [comment]
@qti3e @ry also, the http://propelml.org/ is down...

**Comment by trivikr** [comment]
Closing as the repo README is already updated, and there hasn't been any issue created since this one.
